### ISSUE TITLE
CRM

### ISSUE THREAD

**Issue by carinasoca** [net2phone/uc-roadmap#24]
Objective
To create a tool that enables the client to efficiently manage their customers.

Overview
Building a Cloud CRM where the client can store their customers' contact information, notes, interactions, and based on this data, provide a range of actions such as call campaigns by filtering specific data, bulk SMS/Whatsapp messaging, initiating a Contact Journey from a leads list, among others.

```[tasklist]
### Tasks
- [x] Define CRM requirements and workflows based on business needs. 
- [ ] Develop CRM solution that aligns with your requirements
- [ ] Migrate existing customer data to the new CRM system
- [ ] Train employees and provide support during the CRM launch
```
